name: 'Install and configure Kind cluster'
description: 'Customized Kind-action'

inputs:
  config:
    description: 'Kind config'
    required: true
  olm:
    description: 'install olm'
    required: true
    default: 'false'
  keycloak:
    description: 'install keycloak'
    required: true
    default: 'false'
  prometheus:
    description: 'install prometheus'
    required: true
    default: 'false'

outputs:
  oidc_host:
    value: ${{ steps.install-keycloak.outputs.oidc_host }}
    description: 'Keycloak OIDC host'

runs:
  using: 'composite'
  steps:
    - name: Install Cluster
      uses: helm/kind-action@v1.12.0
      with:
        version: v0.31.0
        node_image: kindest/node:v1.35.0
        kubectl_version: v1.35.0
        cluster_name: kind
        config: ${{ inputs.config }}

    - name: Configure ingress
      shell: bash
      run: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.14.3/deploy/static/provider/kind/deploy.yaml

        kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
    - name: Install prometheus
      if: ${{ inputs.prometheus == 'true'}}
      shell: bash
      run: |
        #install Prometheus
        LATEST=$(curl -s https://api.github.com/repos/prometheus-operator/prometheus-operator/releases/latest | jq -cr .tag_name)
        curl -sL https://github.com/prometheus-operator/prometheus-operator/releases/download/${LATEST}/bundle.yaml | kubectl create -f -
        kubectl wait --for=condition=Ready pods -l  app.kubernetes.io/name=prometheus-operator -n default

    - name: Install olm
      if: ${{ inputs.olm  == 'true'}}
      shell: bash
      run: |
        #install OLM
        kubectl create -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.25.0/crds.yaml
        # wait for a while to be sure CRDs are installed
        sleep 1
        kubectl create -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.25.0/olm.yaml

    - name: Install keycloak
      if: ${{ inputs.keycloak  == 'true'}}
      id: install-keycloak
      shell: bash
      run: |
        bash ci/openshift/tas-keycloak-install.sh kind
        echo "oidc_host=keycloak-internal.keycloak-system.svc" >> $GITHUB_OUTPUT
