apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

helmCharts:
  - name: csi-driver-nfs
    releaseName: 4.11.0
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
