version: "2"
run:
  build-tags:
    - integration
    - upgrade
    - custom_install
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/gomega
        - github.com/onsi/ginkgo/v2
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # TODO: Migrate to GetEventRecorder - https://issues.redhat.com/browse/SECURESIGN-3651
      - linters:
          - staticcheck
        text: "SA1019: manager.GetEventRecorderFor is deprecated"
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
