version: "2"

run:
  allow-parallel-runners: true
  build-tags:
    - integration
    - upgrade
    - custom_install

linters:
  default: none
  enable:
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    rules:
      # Exclude style checks - these are pre-existing and not critical
      - linters:
          - staticcheck
        text: '^ST'
      # Exclude quick fix suggestions
      - linters:
          - staticcheck
        text: '^QF'
      # Exclude deprecated API warnings
      - linters:
          - staticcheck
        text: '^SA1019'

formatters:
  enable:
    - gofmt
    - goimports
