apiVersion: v1
kind: Pod
metadata:
  name: create-ctlog-shard-test1
  namespace: trusted-artifact-signer
spec:
  serviceAccountName: default
  restartPolicy: Never
  securityContext:
    fsGroup: 1000840000
    fsGroupChangePolicy: OnRootMismatch
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: createtree
    image: quay.io/securesign/trillian-createtree@sha256:94b414218ebb1359ffe22549e521b7110852dcc9b5299592f48930ef8daa1e29
    command:
      - /bin/sh
      - -c
      - /createtree --rpc_deadline=240s --admin_server=dns:///trillian-logserver.trusted-artifact-signer.svc:8091 --display_name=ctlog-shard-test1 --tls_cert_file /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000840000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    env:
    - name: SSL_CERT_DIR
      value: /var/run/configs/tas/ca-trust:/var/run/secrets/kubernetes.io/serviceaccount
    volumeMounts:
    - mountPath: /var/run/configs/tas/ca-trust
      name: ca-trust
      readOnly: true
  volumes:
  - name: ca-trust
    projected:
      defaultMode: 420
      sources: null
