apiVersion: rhtas.redhat.com/v1
kind: CTlog
metadata:
  labels:
    app.kubernetes.io/name: securesign-sample
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: ctlog-sample
spec:
  # need to move from spec to spec.logs[]:
  # - treeID
  # - signer
  # - rootCertificates
  # - prefix
  logs: # or config, in .proto named like `LogConfigSet`
    # https://github.com/securesign/certificate-transparency-go/blob/main/trillian/ctfe/configpb/config.proto
    - logId: 1231  # optional - if not set ctlog-createtree job will generate it need to be stored in status field
      prefix: trusted-artifact-signer
      roots: # optional - []SecretKeySelector
        - name: secret
          key: ca.pem
        - name: fulcio-ca-secret
          key: fulcio.pem
      signer: # []CTlogSigner
        type: file
        file:
          privateKeyRef:
            name: secret
            key: key
      notAfterStart: # [time]
      notAfterLimit: # [time]
      mirror: # [bool]
      readonly: # [bool]
      ...
      frozenSTH:
        treeSize: # [int64]
        timestamp: # [time]
        sha256RootHash: # [bytes]
        treeHeadSignature: # [bytes]
    - {} # CTLogConfig
status:
  logs:
    # will need to store spec.logs + autogenerated informations like logId, signer, roots, publicKey