resources:
- manager.yaml
- metrics_service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:9fe463c6ea82e49b7e0321eadd228d5cbe108a5db15a41f4a0ab6b63e0331c17
  name: controller
  newName: registry.redhat.io/rhtas/rhtas-rhel9-operator
