resources:
- manager.yaml
- metrics_service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a87918d77106ccb57696233ba405ea14c7177fca52160da0336365fb8ffc67fe
  name: controller
  newName: registry.redhat.io/rhtas/rhtas-rhel9-operator
