---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rhtas-redhat-com-v1-console
  failurePolicy: Fail
  name: mconsole.kb.io
  rules:
  - apiGroups:
    - rhtas.redhat.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - consoles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rhtas-redhat-com-v1-ctlog
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mctlog.rhtas.redhat.com
  rules:
  - apiGroups:
    - rhtas.redhat.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ctlogs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rhtas-redhat-com-v1-fulcio
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mfulcio.rhtas.redhat.com
  rules:
  - apiGroups:
    - rhtas.redhat.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fulcios
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rhtas-redhat-com-v1-rekor
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mrekor.rhtas.redhat.com
  rules:
  - apiGroups:
    - rhtas.redhat.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rekors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rhtas-redhat-com-v1-securesign
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: msecuresign.rhtas.redhat.com
  rules:
  - apiGroups:
    - rhtas.redhat.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - securesigns
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rhtas-redhat-com-v1-timestampauthority
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mtimestampauthority.rhtas.redhat.com
  rules:
  - apiGroups:
    - rhtas.redhat.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timestampauthorities
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rhtas-redhat-com-v1-trillian
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mtrillian.rhtas.redhat.com
  rules:
  - apiGroups:
    - rhtas.redhat.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - trillians
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rhtas-redhat-com-v1-tuf
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mtuf.rhtas.redhat.com
  rules:
  - apiGroups:
    - rhtas.redhat.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tufs
  sideEffects: None
