apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  labels:
    app.kubernetes.io/name: securesign
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: securesign-sample
spec:
  trillian:
    database:
      create: true
  rekor:
    externalAccess:
      enabled: true
    certificate:
      create: true
      secretName: rekor-private
    monitoring: false
  fulcio:
    externalAccess:
      enabled: true
    config:
      OIDCIssuers:
        "http://keycloak-internal.keycloak-system.svc/auth/realms/sigstore":
          ClientID: "sigstore"
          IssuerURL: "http://keycloak-internal.keycloak-system.svc/auth/realms/sigstore"
          Type: "email"
    certificate:
      create: true
      organizationEmail: jdoe@redhat.com
      organizationName: Red Hat
      secretName: fulcio-cert
    monitoring: false
  tuf:
    externalAccess:
      enabled: true
  ctlog: