# This rule is not used by the project rhtas-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to rhtas.redhat.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rhtas-operator
    app.kubernetes.io/managed-by: kustomize
  name: fulcio-viewer-role
rules:
- apiGroups:
  - rhtas.redhat.com
  resources:
  - fulcios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rhtas.redhat.com
  resources:
  - fulcios/status
  verbs:
  - get
