# permissions for end users to edit securesigns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rhtas-operator
    app.kubernetes.io/managed-by: kustomize
  name: securesign-editor-role
rules:
- apiGroups:
  - rhtas.redhat.com
  resources:
  - securesigns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhtas.redhat.com
  resources:
  - securesigns/status
  verbs:
  - get
