apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: rhtas-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-controller-manager
  namespace: openshift-rhtas-operator
