//go:build integration

package update

import (
	"context"
	"time"

	"github.com/securesign/operator/internal/constants"
	tufAction "github.com/securesign/operator/internal/controller/tuf/constants"

	"github.com/securesign/operator/test/e2e/support/tas"

	fulcioAction "github.com/securesign/operator/internal/controller/fulcio/actions"
	"github.com/securesign/operator/test/e2e/support/tas/ctlog"
	"github.com/securesign/operator/test/e2e/support/tas/fulcio"
	"github.com/securesign/operator/test/e2e/support/tas/tuf"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/securesign/operator/api/v1alpha1"
	ctlogAction "github.com/securesign/operator/internal/controller/ctlog/actions"
	"github.com/securesign/operator/test/e2e/support"
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/types"
	runtimeCli "sigs.k8s.io/controller-runtime/pkg/client"
	yaml "sigs.k8s.io/yaml/goyaml.v2"
)

var _ = Describe("Fulcio update", Ordered, func() {
	SetDefaultEventuallyTimeout(time.Duration(5) * time.Minute)
	cli, _ := support.CreateClient()
	ctx := context.TODO()

	var targetImageName string
	var namespace *v1.Namespace
	var s *v1alpha1.Securesign

	AfterEach(func() {
		if CurrentSpecReport().Failed() && support.IsCIEnvironment() {
			support.DumpNamespace(ctx, cli, namespace.Name)
		}
	})

	BeforeAll(func() {
		namespace = support.CreateTestNamespace(ctx, cli)
		DeferCleanup(func() {
			_ = cli.Delete(ctx, namespace)
		})
		s = securesignResource(namespace)
	})

	BeforeAll(func() {
		targetImageName = support.PrepareImage(ctx)
	})

	Describe("Install with autogenerated certificates", func() {
		BeforeAll(func() {
			Expect(cli.Create(ctx, s)).To(Succeed())
		})

		It("All other components are running", func() {
			tas.VerifyAllComponents(ctx, cli, s, true)
		})
	})

	Describe("Change certificate private key and root CA", func() {
		var tufGeneration, ctlogGeneration, fulcioGeneration int64

		It("stored current deployment observed generations ", func() {
			tufGeneration = getDeploymentGeneration(ctx, cli,
				types.NamespacedName{Namespace: namespace.Name, Name: tufAction.DeploymentName},
			)
			Expect(tufGeneration).Should(BeNumerically(">", 0))
			ctlogGeneration = getDeploymentGeneration(ctx, cli,
				types.NamespacedName{Namespace: namespace.Name, Name: ctlogAction.DeploymentName},
			)
			Expect(ctlogGeneration).Should(BeNumerically(">", 0))
			fulcioGeneration = getDeploymentGeneration(ctx, cli,
				types.NamespacedName{Namespace: namespace.Name, Name: fulcioAction.DeploymentName},
			)
			Expect(fulcioGeneration).Should(BeNumerically(">", 0))
		})

		It("modified fulcio.certificate", func() {
			Eventually(func(g Gomega) error {
				g.Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(s), s)).To(Succeed())
				s.Spec.Fulcio.Certificate = v1alpha1.FulcioCert{
					PrivateKeyRef: &v1alpha1.SecretKeySelector{
						LocalObjectReference: v1alpha1.LocalObjectReference{
							Name: "my-fulcio-secret",
						},
						Key: "private",
					},
					PrivateKeyPasswordRef: &v1alpha1.SecretKeySelector{
						LocalObjectReference: v1alpha1.LocalObjectReference{
							Name: "my-fulcio-secret",
						},
						Key: "password",
					},
					CARef: &v1alpha1.SecretKeySelector{
						LocalObjectReference: v1alpha1.LocalObjectReference{
							Name: "my-fulcio-secret",
						},
						Key: "cert",
					},
				}
				return cli.Update(ctx, s)
			}).WithTimeout(1 * time.Second).Should(Succeed())
		})

		It("has status FulcioCertAvailable == Failure: waiting on my-fulcio-secret", func() {
			Eventually(func(g Gomega) string {
				ctl := fulcio.Get(ctx, cli, namespace.Name, s.Name)()
				g.Expect(ctl).NotTo(BeNil())
				c := meta.FindStatusCondition(ctl.Status.Conditions, fulcioAction.CertCondition)
				g.Expect(c).ToNot(BeNil())
				return c.Reason
			}).Should(Equal(constants.Failure))
		})

		It("created my-fulcio-secret", func() {
			Expect(cli.Create(ctx, fulcio.CreateSecret(namespace.Name, "my-fulcio-secret"))).Should(Succeed())
		})

		It("has status Ready", func() {
			Eventually(func(g Gomega) string {
				ctl := fulcio.Get(ctx, cli, namespace.Name, s.Name)()
				g.Expect(ctl).NotTo(BeNil())
				return meta.FindStatusCondition(ctl.Status.Conditions, constants.Ready).Reason
			}).Should(Equal(constants.Ready))
		})

		It("updated Fulcio deployment", func() {
			Eventually(func() int64 {
				return getDeploymentGeneration(ctx, cli, types.NamespacedName{Namespace: namespace.Name, Name: fulcioAction.DeploymentName})
			}).Should(BeNumerically(">", fulcioGeneration))
		})

		It("updated CTlog deployment", func() {
			Eventually(func() int64 {
				return getDeploymentGeneration(ctx, cli, types.NamespacedName{Namespace: namespace.Name, Name: ctlogAction.DeploymentName})
			}).Should(BeNumerically(">", ctlogGeneration))
		})

		It("update TUF deployment", func() {
			Eventually(func(g Gomega) error {
				g.Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(s), s)).To(Succeed())
				s.Spec.Tuf.Keys = []v1alpha1.TufKey{
					{
						Name: "rekor.pub",
					},
					{
						Name: "fulcio_v1.crt.pem",
						SecretRef: &v1alpha1.SecretKeySelector{
							LocalObjectReference: v1alpha1.LocalObjectReference{
								Name: "my-fulcio-secret",
							},
							Key: "cert",
						},
					},
					{
						Name: "tsa.certchain.pem",
					},
					{
						Name: "ctfe.pub",
					},
				}
				return cli.Update(ctx, s)
			}).WithTimeout(1 * time.Second).Should(Succeed())
			Eventually(func(g Gomega) []v1alpha1.TufKey {
				t := tuf.Get(ctx, cli, namespace.Name, s.Name)()
				return t.Status.Keys
			}).Should(And(HaveLen(4), WithTransform(func(keys []v1alpha1.TufKey) string {
				return keys[1].SecretRef.Name
			}, Equal("my-fulcio-secret"))))
			tuf.RefreshTufRepository(ctx, cli, namespace.Name, s.Name)
		})

		It("verify CTlog and TUF", func() {
			fulcio.Verify(ctx, cli, namespace.Name, s.Name)
			ctlog.Verify(ctx, cli, namespace.Name, s.Name)
			tuf.Verify(ctx, cli, namespace.Name, s.Name)
		})

		It("verify new configuration", func() {
			var fulcioPod *v1.Pod
			Eventually(func(g Gomega) {
				fulcioPod = fulcio.GetServerPod(ctx, cli, namespace.Name)()
				g.Expect(fulcioPod).ToNot(BeNil())
			}).Should(Succeed())
			Expect(fulcioPod.Spec.Volumes).To(ContainElements(And(
				WithTransform(func(v v1.Volume) string { return v.Name }, Equal("fulcio-cert")),
				WithTransform(func(v v1.Volume) string { return v.VolumeSource.Projected.Sources[0].Secret.Name }, Equal("my-fulcio-secret")))))

		})

		It("verify by cosign", func() {
			tas.VerifyByCosign(ctx, cli, s, targetImageName)
		})
	})

	Describe("Changes OIDC configuration", func() {
		var fulcioGeneration int64

		It("stored current deployment observed generations ", func() {
			fulcioGeneration = getDeploymentGeneration(ctx, cli,
				types.NamespacedName{Namespace: namespace.Name, Name: fulcioAction.DeploymentName},
			)
			Expect(fulcioGeneration).Should(BeNumerically(">", 0))
		})

		It("adds new OIDCIssuers", func() {
			Eventually(func(g Gomega) error {
				g.Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(s), s)).To(Succeed())
				s.Spec.Fulcio.Config.OIDCIssuers = append(s.Spec.Fulcio.Config.OIDCIssuers, v1alpha1.OIDCIssuer{
					ClientID:  "fake",
					IssuerURL: "fake",
					Issuer:    "fake",
					Type:      "email",
				})
				return cli.Update(ctx, s)
			}).WithTimeout(1 * time.Second).Should(Succeed())
		})

		It("has status Ready", func() {
			Eventually(func(g Gomega) string {
				ctl := fulcio.Get(ctx, cli, namespace.Name, s.Name)()
				g.Expect(ctl).NotTo(BeNil())
				return meta.FindStatusCondition(ctl.Status.Conditions, constants.Ready).Reason
			}).Should(Equal(constants.Ready))
		})

		It("updated Fulcio deployment", func() {
			Eventually(func() int64 {
				return getDeploymentGeneration(ctx, cli, types.NamespacedName{Namespace: namespace.Name, Name: fulcioAction.DeploymentName})
			}).Should(BeNumerically(">", fulcioGeneration))
		})

		It("verify CTlog and TUF", func() {
			fulcio.Verify(ctx, cli, namespace.Name, s.Name)
		})

		It("verify new configuration", func() {
			var f *v1alpha1.Fulcio
			var fulcioPod *v1.Pod
			Eventually(func(g Gomega) {
				f = fulcio.Get(ctx, cli, namespace.Name, s.Name)()
				g.Expect(f).NotTo(BeNil())
				fulcioPod = fulcio.GetServerPod(ctx, cli, namespace.Name)()
				g.Expect(fulcioPod).NotTo(BeNil())
			}).Should(Succeed())

			Expect(fulcioPod.Spec.Volumes[0].VolumeSource.ConfigMap.Name).To(Equal(f.Status.ServerConfigRef.Name))

			cm := &v1.ConfigMap{}
			Expect(cli.Get(ctx, types.NamespacedName{Namespace: namespace.Name, Name: f.Status.ServerConfigRef.Name}, cm)).To(Succeed())
			config := &fulcioAction.FulcioMapConfig{}
			Expect(yaml.Unmarshal([]byte(cm.Data["config.yaml"]), config)).To(Succeed())
			Expect(config.OIDCIssuers).To(HaveKey("fake"))
		})

		It("verify by cosign", func() {
			tas.VerifyByCosign(ctx, cli, s, targetImageName)
		})
	})
})
