## Append samples you want in your CSV to this file as resources ##
resources:
- rhtas_v1_securesign.yaml
- rhtas_v1_fulcio.yaml
- rhtas_v1_trillian.yaml
- rhtas_v1_rekor.yaml
- rhtas_v1_tuf.yaml
- rhtas_v1_ctlog.yaml
- rhtas_v1_timestampauthority.yaml
- rhtas_v1_console.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
