apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  labels:
    app.kubernetes.io/name: securesign-sample
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: securesign-sample
spec:
  rekor:
    externalAccess:
      enabled: true
    monitoring:
      enabled: true
  trillian:
    database:
      create: true
    monitoring:
      enabled: true
  fulcio:
    externalAccess:
      enabled: true
    config:
      OIDCIssuers:
        - ClientID: "trusted-artifact-signer"
          IssuerURL: "https://your-oidc-issuer-url"
          Issuer: "https://your-oidc-issuer-url"
          Type: "email"
    certificate:
      caType: file
      organizationName: Red Hat
      organizationEmail: jdoe@redhat.com
      commonName: fulcio.hostname
      # To use PKCS#11 instead of file-based CA, replace the above with:
      # caType: pkcs11
      # pkcs11:
      #   pin: "<SECRET_PIN>" Ex: secretpin123
      #   tokenLabel: "<TOKEN_LABEL>" Ex: fulcio
      #   libraryPath: "<FULL_PATH_TO_LIB>" Ex: /usr/lib64/pkcs11/libsofthsm2.so
      #   initContainer:
      #     image: "<INIT_CONTAINER_IMAGE>" Ex: quay.io/rh-ee-sacm/softhsm-init:latest
      #     env:
      #       - name: SOFTHSM2_CONF
      #         value: /etc/softhsm/softhsm2.conf
      #     volumes:
      #       - name: softhsm-config
      #         mountPath: /etc/softhsm
      #         inlineData:
      #           softhsm2.conf: |
      #             directories.tokendir = /var/lib/hsm/tokens
      #             objectstore.backend = file
      #   serverEnv:
      #     - name: SOFTHSM2_CONF
      #       value: /etc/softhsm/softhsm2.conf
    monitoring:
      enabled: true
  tuf:
    externalAccess:
      enabled: true
    signingConfigURLMode: external
    keys:
      - name: rekor.pub
      - name: ctfe.pub
      - name: fulcio_v1.crt.pem
      - name: tsa.certchain.pem
    rootKeySecretRef:
      name: tuf-root-keys
    pvc:
      accessModes:
        - ReadWriteOnce
      retain: true
      size: 100Mi
  ctlog:
    monitoring:
      enabled: true
  tsa:
    externalAccess:
      enabled: true
    monitoring:
      enabled: true
    ntpMonitoring:
      enabled: true
    signer:
      certificateChain:
        rootCA:
          organizationName: Red Hat
          organizationEmail: jdoe@redhat.com
          commonName: tsa.hostname-root
        intermediateCA:
          - organizationName: Red Hat
            organizationEmail: jdoe@redhat.com
            commonName: tsa.hostname-intermediate
        leafCA:
          organizationName: Red Hat
          organizationEmail: jdoe@redhat.com
          commonName: tsa.hostname-leaf
