apiVersion: rhtas.redhat.com/v1alpha1
kind: Trillian
metadata:
  labels:
    app.kubernetes.io/name: securesign-sample
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: trillian-sample
spec:
  database:
    create: true
  server:
    replicas: 1
  signer:
    replicas: 1
