//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth) DeepCopyInto(out *Auth) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecretMount != nil {
		in, out := &in.SecretMount, &out.SecretMount
		*out = make([]SecretKeySelector, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth.
func (in *Auth) DeepCopy() *Auth {
	if in == nil {
		return nil
	}
	out := new(Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackFillRedis) DeepCopyInto(out *BackFillRedis) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackFillRedis.
func (in *BackFillRedis) DeepCopy() *BackFillRedis {
	if in == nil {
		return nil
	}
	out := new(BackFillRedis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIIssuerMetadata) DeepCopyInto(out *CIIssuerMetadata) {
	*out = *in
	if in.DefaultTemplateValues != nil {
		in, out := &in.DefaultTemplateValues, &out.DefaultTemplateValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.ExtensionTemplates = in.ExtensionTemplates
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIIssuerMetadata.
func (in *CIIssuerMetadata) DeepCopy() *CIIssuerMetadata {
	if in == nil {
		return nil
	}
	out := new(CIIssuerMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTlog) DeepCopyInto(out *CTlog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTlog.
func (in *CTlog) DeepCopy() *CTlog {
	if in == nil {
		return nil
	}
	out := new(CTlog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CTlog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTlogList) DeepCopyInto(out *CTlogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CTlog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTlogList.
func (in *CTlogList) DeepCopy() *CTlogList {
	if in == nil {
		return nil
	}
	out := new(CTlogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CTlogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTlogSpec) DeepCopyInto(out *CTlogSpec) {
	*out = *in
	in.PodRequirements.DeepCopyInto(&out.PodRequirements)
	if in.TreeID != nil {
		in, out := &in.TreeID, &out.TreeID
		*out = new(int64)
		**out = **in
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.PrivateKeyPasswordRef != nil {
		in, out := &in.PrivateKeyPasswordRef, &out.PrivateKeyPasswordRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.PublicKeyRef != nil {
		in, out := &in.PublicKeyRef, &out.PublicKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.RootCertificates != nil {
		in, out := &in.RootCertificates, &out.RootCertificates
		*out = make([]SecretKeySelector, len(*in))
		copy(*out, *in)
	}
	out.Monitoring = in.Monitoring
	in.Trillian.DeepCopyInto(&out.Trillian)
	if in.ServerConfigRef != nil {
		in, out := &in.ServerConfigRef, &out.ServerConfigRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTlogSpec.
func (in *CTlogSpec) DeepCopy() *CTlogSpec {
	if in == nil {
		return nil
	}
	out := new(CTlogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTlogStatus) DeepCopyInto(out *CTlogStatus) {
	*out = *in
	if in.ServerConfigRef != nil {
		in, out := &in.ServerConfigRef, &out.ServerConfigRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.PrivateKeyPasswordRef != nil {
		in, out := &in.PrivateKeyPasswordRef, &out.PrivateKeyPasswordRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.PublicKeyRef != nil {
		in, out := &in.PublicKeyRef, &out.PublicKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.RootCertificates != nil {
		in, out := &in.RootCertificates, &out.RootCertificates
		*out = make([]SecretKeySelector, len(*in))
		copy(*out, *in)
	}
	if in.TreeID != nil {
		in, out := &in.TreeID, &out.TreeID
		*out = new(int64)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTlogStatus.
func (in *CTlogStatus) DeepCopy() *CTlogStatus {
	if in == nil {
		return nil
	}
	out := new(CTlogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateChain) DeepCopyInto(out *CertificateChain) {
	*out = *in
	if in.CertificateChainRef != nil {
		in, out := &in.CertificateChainRef, &out.CertificateChainRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.RootCA != nil {
		in, out := &in.RootCA, &out.RootCA
		*out = new(TsaCertificateAuthority)
		(*in).DeepCopyInto(*out)
	}
	if in.IntermediateCA != nil {
		in, out := &in.IntermediateCA, &out.IntermediateCA
		*out = make([]*TsaCertificateAuthority, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TsaCertificateAuthority)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.LeafCA != nil {
		in, out := &in.LeafCA, &out.LeafCA
		*out = new(TsaCertificateAuthority)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateChain.
func (in *CertificateChain) DeepCopy() *CertificateChain {
	if in == nil {
		return nil
	}
	out := new(CertificateChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CtlogService) DeepCopyInto(out *CtlogService) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CtlogService.
func (in *CtlogService) DeepCopy() *CtlogService {
	if in == nil {
		return nil
	}
	out := new(CtlogService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extensions) DeepCopyInto(out *Extensions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extensions.
func (in *Extensions) DeepCopy() *Extensions {
	if in == nil {
		return nil
	}
	out := new(Extensions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAccess) DeepCopyInto(out *ExternalAccess) {
	*out = *in
	if in.RouteSelectorLabels != nil {
		in, out := &in.RouteSelectorLabels, &out.RouteSelectorLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAccess.
func (in *ExternalAccess) DeepCopy() *ExternalAccess {
	if in == nil {
		return nil
	}
	out := new(ExternalAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *File) DeepCopyInto(out *File) {
	*out = *in
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new File.
func (in *File) DeepCopy() *File {
	if in == nil {
		return nil
	}
	out := new(File)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Fulcio) DeepCopyInto(out *Fulcio) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Fulcio.
func (in *Fulcio) DeepCopy() *Fulcio {
	if in == nil {
		return nil
	}
	out := new(Fulcio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Fulcio) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FulcioCert) DeepCopyInto(out *FulcioCert) {
	*out = *in
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.PrivateKeyPasswordRef != nil {
		in, out := &in.PrivateKeyPasswordRef, &out.PrivateKeyPasswordRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.CARef != nil {
		in, out := &in.CARef, &out.CARef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FulcioCert.
func (in *FulcioCert) DeepCopy() *FulcioCert {
	if in == nil {
		return nil
	}
	out := new(FulcioCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FulcioConfig) DeepCopyInto(out *FulcioConfig) {
	*out = *in
	if in.OIDCIssuers != nil {
		in, out := &in.OIDCIssuers, &out.OIDCIssuers
		*out = make([]OIDCIssuer, len(*in))
		copy(*out, *in)
	}
	if in.MetaIssuers != nil {
		in, out := &in.MetaIssuers, &out.MetaIssuers
		*out = make([]OIDCIssuer, len(*in))
		copy(*out, *in)
	}
	if in.CIIssuerMetadata != nil {
		in, out := &in.CIIssuerMetadata, &out.CIIssuerMetadata
		*out = make([]CIIssuerMetadata, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FulcioConfig.
func (in *FulcioConfig) DeepCopy() *FulcioConfig {
	if in == nil {
		return nil
	}
	out := new(FulcioConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FulcioList) DeepCopyInto(out *FulcioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Fulcio, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FulcioList.
func (in *FulcioList) DeepCopy() *FulcioList {
	if in == nil {
		return nil
	}
	out := new(FulcioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FulcioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FulcioSpec) DeepCopyInto(out *FulcioSpec) {
	*out = *in
	in.PodRequirements.DeepCopyInto(&out.PodRequirements)
	in.ExternalAccess.DeepCopyInto(&out.ExternalAccess)
	in.Ctlog.DeepCopyInto(&out.Ctlog)
	in.Config.DeepCopyInto(&out.Config)
	in.Certificate.DeepCopyInto(&out.Certificate)
	out.Monitoring = in.Monitoring
	if in.TrustedCA != nil {
		in, out := &in.TrustedCA, &out.TrustedCA
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FulcioSpec.
func (in *FulcioSpec) DeepCopy() *FulcioSpec {
	if in == nil {
		return nil
	}
	out := new(FulcioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FulcioStatus) DeepCopyInto(out *FulcioStatus) {
	*out = *in
	if in.ServerConfigRef != nil {
		in, out := &in.ServerConfigRef, &out.ServerConfigRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(FulcioCert)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FulcioStatus.
func (in *FulcioStatus) DeepCopy() *FulcioStatus {
	if in == nil {
		return nil
	}
	out := new(FulcioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KMS) DeepCopyInto(out *KMS) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(Auth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KMS.
func (in *KMS) DeepCopy() *KMS {
	if in == nil {
		return nil
	}
	out := new(KMS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfig.
func (in *MonitoringConfig) DeepCopy() *MonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTPMonitoring) DeepCopyInto(out *NTPMonitoring) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(NtpMonitoringConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTPMonitoring.
func (in *NTPMonitoring) DeepCopy() *NTPMonitoring {
	if in == nil {
		return nil
	}
	out := new(NTPMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NtpMonitoringConfig) DeepCopyInto(out *NtpMonitoringConfig) {
	*out = *in
	if in.NtpConfigRef != nil {
		in, out := &in.NtpConfigRef, &out.NtpConfigRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NtpMonitoringConfig.
func (in *NtpMonitoringConfig) DeepCopy() *NtpMonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(NtpMonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCIssuer) DeepCopyInto(out *OIDCIssuer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCIssuer.
func (in *OIDCIssuer) DeepCopy() *OIDCIssuer {
	if in == nil {
		return nil
	}
	out := new(OIDCIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRequirements) DeepCopyInto(out *PodRequirements) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRequirements.
func (in *PodRequirements) DeepCopy() *PodRequirements {
	if in == nil {
		return nil
	}
	out := new(PodRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pvc) DeepCopyInto(out *Pvc) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Retain != nil {
		in, out := &in.Retain, &out.Retain
		*out = new(bool)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pvc.
func (in *Pvc) DeepCopy() *Pvc {
	if in == nil {
		return nil
	}
	out := new(Pvc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rekor) DeepCopyInto(out *Rekor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rekor.
func (in *Rekor) DeepCopy() *Rekor {
	if in == nil {
		return nil
	}
	out := new(Rekor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Rekor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RekorList) DeepCopyInto(out *RekorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Rekor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RekorList.
func (in *RekorList) DeepCopy() *RekorList {
	if in == nil {
		return nil
	}
	out := new(RekorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RekorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RekorLogRange) DeepCopyInto(out *RekorLogRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RekorLogRange.
func (in *RekorLogRange) DeepCopy() *RekorLogRange {
	if in == nil {
		return nil
	}
	out := new(RekorLogRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RekorSearchUI) DeepCopyInto(out *RekorSearchUI) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RouteSelectorLabels != nil {
		in, out := &in.RouteSelectorLabels, &out.RouteSelectorLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RekorSearchUI.
func (in *RekorSearchUI) DeepCopy() *RekorSearchUI {
	if in == nil {
		return nil
	}
	out := new(RekorSearchUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RekorSigner) DeepCopyInto(out *RekorSigner) {
	*out = *in
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.KeyRef != nil {
		in, out := &in.KeyRef, &out.KeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RekorSigner.
func (in *RekorSigner) DeepCopy() *RekorSigner {
	if in == nil {
		return nil
	}
	out := new(RekorSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RekorSpec) DeepCopyInto(out *RekorSpec) {
	*out = *in
	if in.TreeID != nil {
		in, out := &in.TreeID, &out.TreeID
		*out = new(int64)
		**out = **in
	}
	in.Trillian.DeepCopyInto(&out.Trillian)
	in.ExternalAccess.DeepCopyInto(&out.ExternalAccess)
	out.Monitoring = in.Monitoring
	in.RekorSearchUI.DeepCopyInto(&out.RekorSearchUI)
	in.Signer.DeepCopyInto(&out.Signer)
	in.SearchIndex.DeepCopyInto(&out.SearchIndex)
	in.Pvc.DeepCopyInto(&out.Pvc)
	in.BackFillRedis.DeepCopyInto(&out.BackFillRedis)
	if in.Sharding != nil {
		in, out := &in.Sharding, &out.Sharding
		*out = make([]RekorLogRange, len(*in))
		copy(*out, *in)
	}
	if in.TrustedCA != nil {
		in, out := &in.TrustedCA, &out.TrustedCA
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(Auth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RekorSpec.
func (in *RekorSpec) DeepCopy() *RekorSpec {
	if in == nil {
		return nil
	}
	out := new(RekorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RekorStatus) DeepCopyInto(out *RekorStatus) {
	*out = *in
	if in.PublicKeyRef != nil {
		in, out := &in.PublicKeyRef, &out.PublicKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.ServerConfigRef != nil {
		in, out := &in.ServerConfigRef, &out.ServerConfigRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	in.Signer.DeepCopyInto(&out.Signer)
	in.SearchIndex.DeepCopyInto(&out.SearchIndex)
	if in.TreeID != nil {
		in, out := &in.TreeID, &out.TreeID
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RekorStatus.
func (in *RekorStatus) DeepCopy() *RekorStatus {
	if in == nil {
		return nil
	}
	out := new(RekorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchIndex) DeepCopyInto(out *SearchIndex) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchIndex.
func (in *SearchIndex) DeepCopy() *SearchIndex {
	if in == nil {
		return nil
	}
	out := new(SearchIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchIndexStatus) DeepCopyInto(out *SearchIndexStatus) {
	*out = *in
	in.TLS.DeepCopyInto(&out.TLS)
	if in.DbPasswordRef != nil {
		in, out := &in.DbPasswordRef, &out.DbPasswordRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchIndexStatus.
func (in *SearchIndexStatus) DeepCopy() *SearchIndexStatus {
	if in == nil {
		return nil
	}
	out := new(SearchIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Securesign) DeepCopyInto(out *Securesign) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Securesign.
func (in *Securesign) DeepCopy() *Securesign {
	if in == nil {
		return nil
	}
	out := new(Securesign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Securesign) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuresignFulcioStatus) DeepCopyInto(out *SecuresignFulcioStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuresignFulcioStatus.
func (in *SecuresignFulcioStatus) DeepCopy() *SecuresignFulcioStatus {
	if in == nil {
		return nil
	}
	out := new(SecuresignFulcioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuresignList) DeepCopyInto(out *SecuresignList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Securesign, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuresignList.
func (in *SecuresignList) DeepCopy() *SecuresignList {
	if in == nil {
		return nil
	}
	out := new(SecuresignList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecuresignList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuresignRekorStatus) DeepCopyInto(out *SecuresignRekorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuresignRekorStatus.
func (in *SecuresignRekorStatus) DeepCopy() *SecuresignRekorStatus {
	if in == nil {
		return nil
	}
	out := new(SecuresignRekorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuresignSpec) DeepCopyInto(out *SecuresignSpec) {
	*out = *in
	in.Rekor.DeepCopyInto(&out.Rekor)
	in.Fulcio.DeepCopyInto(&out.Fulcio)
	in.Trillian.DeepCopyInto(&out.Trillian)
	in.Tuf.DeepCopyInto(&out.Tuf)
	in.Ctlog.DeepCopyInto(&out.Ctlog)
	if in.TimestampAuthority != nil {
		in, out := &in.TimestampAuthority, &out.TimestampAuthority
		*out = new(TimestampAuthoritySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuresignSpec.
func (in *SecuresignSpec) DeepCopy() *SecuresignSpec {
	if in == nil {
		return nil
	}
	out := new(SecuresignSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuresignStatus) DeepCopyInto(out *SecuresignStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.RekorStatus = in.RekorStatus
	out.FulcioStatus = in.FulcioStatus
	out.TufStatus = in.TufStatus
	out.TSAStatus = in.TSAStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuresignStatus.
func (in *SecuresignStatus) DeepCopy() *SecuresignStatus {
	if in == nil {
		return nil
	}
	out := new(SecuresignStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuresignTSAStatus) DeepCopyInto(out *SecuresignTSAStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuresignTSAStatus.
func (in *SecuresignTSAStatus) DeepCopy() *SecuresignTSAStatus {
	if in == nil {
		return nil
	}
	out := new(SecuresignTSAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuresignTufStatus) DeepCopyInto(out *SecuresignTufStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuresignTufStatus.
func (in *SecuresignTufStatus) DeepCopy() *SecuresignTufStatus {
	if in == nil {
		return nil
	}
	out := new(SecuresignTufStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLS) DeepCopyInto(out *TLS) {
	*out = *in
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.CertRef != nil {
		in, out := &in.CertRef, &out.CertRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLS.
func (in *TLS) DeepCopy() *TLS {
	if in == nil {
		return nil
	}
	out := new(TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampAuthority) DeepCopyInto(out *TimestampAuthority) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampAuthority.
func (in *TimestampAuthority) DeepCopy() *TimestampAuthority {
	if in == nil {
		return nil
	}
	out := new(TimestampAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimestampAuthority) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampAuthorityList) DeepCopyInto(out *TimestampAuthorityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimestampAuthority, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampAuthorityList.
func (in *TimestampAuthorityList) DeepCopy() *TimestampAuthorityList {
	if in == nil {
		return nil
	}
	out := new(TimestampAuthorityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimestampAuthorityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampAuthoritySigner) DeepCopyInto(out *TimestampAuthoritySigner) {
	*out = *in
	in.CertificateChain.DeepCopyInto(&out.CertificateChain)
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(File)
		(*in).DeepCopyInto(*out)
	}
	if in.Kms != nil {
		in, out := &in.Kms, &out.Kms
		*out = new(KMS)
		(*in).DeepCopyInto(*out)
	}
	if in.Tink != nil {
		in, out := &in.Tink, &out.Tink
		*out = new(Tink)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampAuthoritySigner.
func (in *TimestampAuthoritySigner) DeepCopy() *TimestampAuthoritySigner {
	if in == nil {
		return nil
	}
	out := new(TimestampAuthoritySigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampAuthoritySpec) DeepCopyInto(out *TimestampAuthoritySpec) {
	*out = *in
	in.PodRequirements.DeepCopyInto(&out.PodRequirements)
	in.ExternalAccess.DeepCopyInto(&out.ExternalAccess)
	in.Signer.DeepCopyInto(&out.Signer)
	out.Monitoring = in.Monitoring
	if in.TrustedCA != nil {
		in, out := &in.TrustedCA, &out.TrustedCA
		*out = new(LocalObjectReference)
		**out = **in
	}
	in.NTPMonitoring.DeepCopyInto(&out.NTPMonitoring)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampAuthoritySpec.
func (in *TimestampAuthoritySpec) DeepCopy() *TimestampAuthoritySpec {
	if in == nil {
		return nil
	}
	out := new(TimestampAuthoritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampAuthorityStatus) DeepCopyInto(out *TimestampAuthorityStatus) {
	*out = *in
	if in.NTPMonitoring != nil {
		in, out := &in.NTPMonitoring, &out.NTPMonitoring
		*out = new(NTPMonitoring)
		(*in).DeepCopyInto(*out)
	}
	if in.Signer != nil {
		in, out := &in.Signer, &out.Signer
		*out = new(TimestampAuthoritySigner)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampAuthorityStatus.
func (in *TimestampAuthorityStatus) DeepCopy() *TimestampAuthorityStatus {
	if in == nil {
		return nil
	}
	out := new(TimestampAuthorityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tink) DeepCopyInto(out *Tink) {
	*out = *in
	if in.KeysetRef != nil {
		in, out := &in.KeysetRef, &out.KeysetRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(Auth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tink.
func (in *Tink) DeepCopy() *Tink {
	if in == nil {
		return nil
	}
	out := new(Tink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trillian) DeepCopyInto(out *Trillian) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trillian.
func (in *Trillian) DeepCopy() *Trillian {
	if in == nil {
		return nil
	}
	out := new(Trillian)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Trillian) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrillianDB) DeepCopyInto(out *TrillianDB) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
	if in.DatabaseSecretRef != nil {
		in, out := &in.DatabaseSecretRef, &out.DatabaseSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	in.Pvc.DeepCopyInto(&out.Pvc)
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrillianDB.
func (in *TrillianDB) DeepCopy() *TrillianDB {
	if in == nil {
		return nil
	}
	out := new(TrillianDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrillianList) DeepCopyInto(out *TrillianList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Trillian, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrillianList.
func (in *TrillianList) DeepCopy() *TrillianList {
	if in == nil {
		return nil
	}
	out := new(TrillianList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrillianList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrillianLogServer) DeepCopyInto(out *TrillianLogServer) {
	*out = *in
	in.PodRequirements.DeepCopyInto(&out.PodRequirements)
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrillianLogServer.
func (in *TrillianLogServer) DeepCopy() *TrillianLogServer {
	if in == nil {
		return nil
	}
	out := new(TrillianLogServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrillianLogSigner) DeepCopyInto(out *TrillianLogSigner) {
	*out = *in
	in.PodRequirements.DeepCopyInto(&out.PodRequirements)
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrillianLogSigner.
func (in *TrillianLogSigner) DeepCopy() *TrillianLogSigner {
	if in == nil {
		return nil
	}
	out := new(TrillianLogSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrillianService) DeepCopyInto(out *TrillianService) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrillianService.
func (in *TrillianService) DeepCopy() *TrillianService {
	if in == nil {
		return nil
	}
	out := new(TrillianService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrillianSpec) DeepCopyInto(out *TrillianSpec) {
	*out = *in
	in.Db.DeepCopyInto(&out.Db)
	out.Monitoring = in.Monitoring
	in.LogServer.DeepCopyInto(&out.LogServer)
	in.LogSigner.DeepCopyInto(&out.LogSigner)
	if in.TrustedCA != nil {
		in, out := &in.TrustedCA, &out.TrustedCA
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrillianSpec.
func (in *TrillianSpec) DeepCopy() *TrillianSpec {
	if in == nil {
		return nil
	}
	out := new(TrillianSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrillianStatus) DeepCopyInto(out *TrillianStatus) {
	*out = *in
	in.Db.DeepCopyInto(&out.Db)
	in.LogServer.DeepCopyInto(&out.LogServer)
	in.LogSigner.DeepCopyInto(&out.LogSigner)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrillianStatus.
func (in *TrillianStatus) DeepCopy() *TrillianStatus {
	if in == nil {
		return nil
	}
	out := new(TrillianStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TsaCertificateAuthority) DeepCopyInto(out *TsaCertificateAuthority) {
	*out = *in
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TsaCertificateAuthority.
func (in *TsaCertificateAuthority) DeepCopy() *TsaCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(TsaCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tuf) DeepCopyInto(out *Tuf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tuf.
func (in *Tuf) DeepCopy() *Tuf {
	if in == nil {
		return nil
	}
	out := new(Tuf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tuf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TufKey) DeepCopyInto(out *TufKey) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TufKey.
func (in *TufKey) DeepCopy() *TufKey {
	if in == nil {
		return nil
	}
	out := new(TufKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TufList) DeepCopyInto(out *TufList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tuf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TufList.
func (in *TufList) DeepCopy() *TufList {
	if in == nil {
		return nil
	}
	out := new(TufList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TufList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TufPvc) DeepCopyInto(out *TufPvc) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Retain != nil {
		in, out := &in.Retain, &out.Retain
		*out = new(bool)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TufPvc.
func (in *TufPvc) DeepCopy() *TufPvc {
	if in == nil {
		return nil
	}
	out := new(TufPvc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TufSpec) DeepCopyInto(out *TufSpec) {
	*out = *in
	in.ExternalAccess.DeepCopyInto(&out.ExternalAccess)
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]TufKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RootKeySecretRef != nil {
		in, out := &in.RootKeySecretRef, &out.RootKeySecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	in.Pvc.DeepCopyInto(&out.Pvc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TufSpec.
func (in *TufSpec) DeepCopy() *TufSpec {
	if in == nil {
		return nil
	}
	out := new(TufSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TufStatus) DeepCopyInto(out *TufStatus) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]TufKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TufStatus.
func (in *TufStatus) DeepCopy() *TufStatus {
	if in == nil {
		return nil
	}
	out := new(TufStatus)
	in.DeepCopyInto(out)
	return out
}
