apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: trusted-artifact-signer-realm
spec:
  keycloakCRName: keycloak
  realm:
    id: trusted-artifact-signer
    realm: trusted-artifact-signer
    displayName: Red-Hat-Trusted-Artifact-Signer
    enabled: true
    sslRequired: none
    clients:
      - clientId: trusted-artifact-signer
        name: trusted-artifact-signer
        description: Client for Red Hat Trusted Artifact Signer authentication
        protocol: openid-connect
        publicClient: true
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
        implicitFlowEnabled: false
        defaultClientScopes: ["profile","email"]
        redirectUris:
          - "*"
          - "urn:ietf:wg:oauth:2.0:oob"
        attributes:
          "request.object.signature.alg": "RS256"
          "user.info.response.signature.alg": "RS256"
        protocolMappers:
          - name: email
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            config:
              "user.attribute": "email"
              "claim.name": "email"
              "jsonType.label": "String"
              "id.token.claim": "true"
              "userinfo.token.claim": "true"
          - name: email-verified
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            config:
              "user.attribute": "emailVerified"
              "claim.name": "email-verified"
              "id.token.claim": "true"
              "userinfo.token.claim": "true"
          - name: audience
            protocol: openid-connect
            protocolMapper: oidc-hardcoded-claim-mapper
            config:
              "claim.name": "aud"
              "claim.value": "trusted-artifact-signer"
              "id.token.claim": "true"
              "access.token.claim": "true"
              "userinfo.token.claim": "true"
    users:
      - username: jdoe
        enabled: true
        emailVerified: true
        email: jdoe@redhat.com
        firstName: Jane
        lastName: Doe
        credentials:
          - type: password
            value: secure
            temporary: false
