//go:build integration

package install

import (
	"github.com/securesign/operator/test/e2e/support/postgresql"
	"github.com/securesign/operator/test/e2e/support/steps"
	"github.com/securesign/operator/test/e2e/support/tas"
	"github.com/securesign/operator/test/e2e/support/tas/cosign"
	"github.com/securesign/operator/test/e2e/support/tas/securesign"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	rhtasv1 "github.com/securesign/operator/api/v1"
	"github.com/securesign/operator/test/e2e/support"
	v1 "k8s.io/api/core/v1"
)

var _ = Describe("Securesign install with in-cluster services and internal TUF signing config", Ordered, func() {
	cli, _ := support.CreateClient()

	var namespace *v1.Namespace
	var s *rhtasv1.Securesign
	var targetImageName string
	var fipsEnabled bool

	BeforeAll(steps.DetectAndConfigureFIPS(cli, func(enabled bool) {
		fipsEnabled = enabled
	}))

	BeforeAll(steps.CreateNamespace(cli, func(new *v1.Namespace) {
		namespace = new
	}))

	BeforeAll(func(ctx SpecContext) {
		if fipsEnabled {
			Expect(postgresql.CreateDB(ctx, cli, namespace.Name, postgresql.DefaultSecretName, "fips-password")).To(Succeed())
			postgresql.WaitAndLoadSchema(ctx, cli, namespace.Name)
		}
	})

	BeforeAll(func(ctx SpecContext) {
		s = securesign.Create(namespace.Name, "test",
			securesign.WithTSA(),
			securesign.WithGeneratedCerts(),
			func(ss *rhtasv1.Securesign) {
				if fipsEnabled {
					securesign.WithExternalPostgresDB(namespace.Name, postgresql.DefaultSecretName)(ss)
				} else {
					securesign.WithManagedDatabase()(ss)
				}
			},
			securesign.WithDefaultOIDC(),
			securesign.WithNTPMonitoring(),
		)
	})

	BeforeAll(func(ctx SpecContext) {
		targetImageName = support.PrepareImage(ctx)
	})

	Describe("Install with autogenerated certificates (no external routes)", func() {
		BeforeAll(func(ctx SpecContext) {
			Expect(cli.Create(ctx, s)).To(Succeed())
		})

		It("All other components are running", func(ctx SpecContext) {
			tas.VerifyAllComponents(ctx, cli, s, !fipsEnabled, true)
		})

		It("Securesign status exposes in-cluster service URLs", func(ctx SpecContext) {
			s = securesign.Get(ctx, cli, namespace.Name, s.Name)
			Expect(s.Status.TufStatus.Url).To(ContainSubstring(".svc"))
			Expect(s.Status.FulcioStatus.Url).To(ContainSubstring(".svc"))
			Expect(s.Status.RekorStatus.Url).To(ContainSubstring(".svc"))
			Expect(s.Status.TSAStatus.Url).To(ContainSubstring(".svc"))
		})

		It("Sign image with cosign cli", func(ctx SpecContext) {
			cosign := cosign.NewInClusterCosign(namespace.Name, s.Status.TufStatus.Url, cli)
			cosign.VerifyByCosign(ctx, targetImageName)
		})

	})
})
