//go:build integration

package install

import (
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/certificate-transparency-go/trillian/ctfe/configpb"
	"github.com/google/trillian/crypto/keyspb"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	rhtasv1 "github.com/securesign/operator/api/v1"
	ctlogAction "github.com/securesign/operator/internal/controller/ctlog/actions"
	"github.com/securesign/operator/internal/labels"
	"github.com/securesign/operator/internal/utils/kubernetes"
	"github.com/securesign/operator/test/e2e/support"
	testKubernetes "github.com/securesign/operator/test/e2e/support/kubernetes"
	"github.com/securesign/operator/test/e2e/support/postgresql"
	"github.com/securesign/operator/test/e2e/support/steps"
	"github.com/securesign/operator/test/e2e/support/tas/ctlog"
	"github.com/securesign/operator/test/e2e/support/tas/securesign"
	"google.golang.org/protobuf/encoding/prototext"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/known/timestamppb"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/utils/ptr"
	runtimeCli "sigs.k8s.io/controller-runtime/pkg/client"
)

var _ = Describe("CTlog PKCS#11 sharding configuration", Ordered, func() {
	SetDefaultEventuallyTimeout(time.Duration(10) * time.Minute)
	cli, _ := support.CreateClient()

	var namespace *v1.Namespace
	var s *rhtasv1.Securesign
	var fipsEnabled bool
	var runningTimestamp time.Time
	var newTreeId int64

	BeforeAll(steps.DetectAndConfigureFIPS(cli, func(enabled bool) {
		fipsEnabled = enabled
	}))

	BeforeAll(steps.CreateNamespace(cli, func(new *v1.Namespace) {
		namespace = new
	}))

	BeforeAll(func(ctx SpecContext) {
		if fipsEnabled {
			Expect(postgresql.CreateDB(ctx, cli, namespace.Name, postgresql.DefaultSecretName, "fips-password")).To(Succeed())
			postgresql.WaitAndLoadSchema(ctx, cli, namespace.Name)
		}
	})

	BeforeAll(func(ctx SpecContext) {
		s = securesign.Create(namespace.Name, "test",
			securesign.ChooseDefaults(fipsEnabled, namespace.Name),
		)
	})

	Describe("Install with autogenerated certificates", func() {
		BeforeAll(func(ctx SpecContext) {
			Expect(cli.Create(ctx, s)).To(Succeed())
		})

		It("All components are running", func(ctx SpecContext) {
			Eventually(func(g Gomega) bool {
				list := &v1.PodList{}
				g.Expect(cli.List(ctx, list, runtimeCli.InNamespace(namespace.Name), runtimeCli.MatchingLabels{labels.LabelAppComponent: ctlogAction.ComponentName})).To(Succeed())
				return len(list.Items) > 0
			}).Should(BeTrue())
			runningTimestamp = time.Now()
		})
	})

	Describe("Configure CTlog PKCS#11 sharding", func() {
		var oldTreeId *int64
		var oldConfig *v1.Secret
		var oldPublicKey []byte

		It("Get current ctlog tree information", func(ctx SpecContext) {
			c := ctlog.Get(ctx, cli, namespace.Name, s.Name)
			Expect(c).ToNot(BeNil())
			oldTreeId = c.Status.TreeID
			Expect(oldTreeId).ToNot(BeNil())

			var err error
			oldConfig, err = kubernetes.GetSecret(ctx, cli, namespace.Name, c.Status.ServerConfigRef.Name)
			Expect(err).ToNot(HaveOccurred())
			Expect(oldConfig).ToNot(BeNil())

			oldPublicKey = oldConfig.Data["public"]
			Expect(oldPublicKey).ToNot(BeEmpty())
		})

		It("Freeze the current tree", func(ctx SpecContext) {
			drainingPod := updateTree(namespace.Name, oldTreeId, "DRAINING")
			Expect(cli.Create(ctx, drainingPod)).To(Succeed())
			Eventually(func(gomega Gomega) bool {
				gomega.Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(drainingPod), drainingPod)).To(Succeed())
				return drainingPod.Status.Phase == v1.PodSucceeded
			}).Should(BeTrue())

			freezePod := updateTree(namespace.Name, oldTreeId, "FROZEN")
			Expect(cli.Create(ctx, freezePod)).To(Succeed())
			Eventually(func(gomega Gomega) bool {
				gomega.Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(freezePod), freezePod)).To(Succeed())
				return freezePod.Status.Phase == v1.PodSucceeded
			}).Should(BeTrue())
		})

		It("Create new tree for active log", func(ctx SpecContext) {
			createPod := createTree(namespace.Name, "ctlog-pkcs11-sharding-tree")
			Expect(cli.Create(ctx, createPod)).To(Succeed())
			Eventually(func(gomega Gomega) bool {
				gomega.Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(createPod), createPod)).To(Succeed())
				return createPod.Status.Phase == v1.PodSucceeded
			}).Should(BeTrue())

			createTreeLog, err := testKubernetes.GetPodLogs(ctx, createPod.Name, "createtree", namespace.Name)
			Expect(err).ToNot(HaveOccurred())
			lines := strings.Split(strings.TrimSpace(createTreeLog), "\n")
			newTreeId, err = strconv.ParseInt(lines[len(lines)-1], 10, 64)
			Expect(err).ToNot(HaveOccurred())
		})

		It("Configure PKCS#11 sharding with new tree", func(ctx SpecContext) {

			Eventually(func() error {
				s := securesign.Get(ctx, cli, namespace.Name, "test")

				if newTreeId == 0 {
					return fmt.Errorf("new tree ID not set")
				}

				secretName := "ctlog-pkcs11-sharding-config"
				newCtlogSecret := ctlog.CreateSecret(namespace.Name, secretName)

				// Prepare config with PKCS#11 sharding
				cfg := &configpb.LogMultiConfig{}
				now := time.Now()
				timestamp := &timestamppb.Timestamp{
					Seconds: now.Unix(), Nanos: int32(now.Nanosecond()),
				}
				Expect(prototext.Unmarshal(oldConfig.Data["config"], cfg)).To(Succeed())

				// First config entry is the frozen shard
				frozen := cfg.LogConfigs.Config[0]
				Expect(frozen).ToNot(BeNil())

				// Create a copy for the active shard
				cfg.LogConfigs.Config = append(cfg.LogConfigs.Config, proto.Clone(frozen).(*configpb.LogConfig))
				active := cfg.LogConfigs.Config[1]

				// Configure the frozen shard
				frozen.LogId = *oldTreeId
				frozen.NotAfterLimit = timestamp
				frozen.Prefix = "trusted-artifact-signer-shard-0"
				frozenKey := &keyspb.PEMKeyFile{}
				Expect(anypb.UnmarshalTo(frozen.PrivateKey, frozenKey, proto.UnmarshalOptions{})).To(Succeed())
				frozenKey.Path = "/ctfe-keys/private-0"
				frozenAnyKey, err := anypb.New(frozenKey)
				Expect(err).ToNot(HaveOccurred())
				frozen.PrivateKey = frozenAnyKey

				// Configure the active shard
				active.LogId = newTreeId
				active.Prefix = "trusted-artifact-signer"
				password := ""
				if pwd, ok := newCtlogSecret.Data["password"]; ok {
					password = string(pwd)
				}
				activeAnyKey, err := anypb.New(&keyspb.PEMKeyFile{
					Path:     "/ctfe-keys/private",
					Password: password,
				})
				Expect(err).ToNot(HaveOccurred())
				active.PrivateKey = activeAnyKey
				active.PublicKey = nil
				active.NotAfterStart = timestamp

				configdata, err := prototext.Marshal(cfg)
				Expect(err).ToNot(HaveOccurred())
				newCtlogSecret.Data["config"] = configdata
				newCtlogSecret.Data["fulcio"] = oldConfig.Data["fulcio"]
				newCtlogSecret.Data["private-0"] = oldConfig.Data["private"]
				newCtlogSecret.Data["public-0"] = oldConfig.Data["public"]

				Expect(cli.Create(ctx, newCtlogSecret)).To(Succeed())

				// Update securesign resource with PKCS#11 sharding configuration
				Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(s), s)).To(Succeed())

				s.Spec.Ctlog.TreeID = ptr.To(newTreeId)

				if s.Spec.Ctlog.Signer.File == nil {
					s.Spec.Ctlog.Signer.File = &rhtasv1.CTlogFile{}
				}
				s.Spec.Ctlog.Signer.File.PrivateKeyRef = &rhtasv1.SecretKeySelector{
					LocalObjectReference: rhtasv1.LocalObjectReference{
						Name: secretName,
					},
					Key: "private",
				}

				s.Spec.Ctlog.Signer.File.PublicKeyRef = &rhtasv1.SecretKeySelector{
					LocalObjectReference: rhtasv1.LocalObjectReference{
						Name: secretName,
					},
					Key: "public",
				}

				// Add PKCS#11 sharding configuration
				s.Spec.Ctlog.Sharding = []rhtasv1.CTlogLogRange{
					{
						TreeID: *oldTreeId,
						Type:   "file",
						Prefix: "shard-0",
						PublicKeyRef: &rhtasv1.SecretKeySelector{
							LocalObjectReference: rhtasv1.LocalObjectReference{
								Name: secretName,
							},
							Key: "public-0",
						},
						PrivateKeyRef: &rhtasv1.SecretKeySelector{
							LocalObjectReference: rhtasv1.LocalObjectReference{
								Name: secretName,
							},
							Key: "private-0",
						},
					},
					{
						TreeID:     *oldTreeId + 1,
						Type:       "pkcs11",
						Prefix:     "shard-hsm",
						ModulePath: "/usr/lib/softhsm/libsofthsm2.so",
						TokenLabel: "test-ctlog-hsm",
						PinSecretRef: &rhtasv1.SecretKeySelector{
							LocalObjectReference: rhtasv1.LocalObjectReference{
								Name: "ctlog-hsm-pin",
							},
							Key: "pin",
						},
						PublicKeyRef: &rhtasv1.SecretKeySelector{
							LocalObjectReference: rhtasv1.LocalObjectReference{
								Name: secretName,
							},
							Key: "public-0",
						},
					},
				}

				return cli.Update(ctx, s)
			}).Should(Succeed())
		})

		It("Verify CTlog deployment is updated with PKCS#11 sharding config", func(ctx SpecContext) {
			Eventually(func(g Gomega) bool {
				list := &v1.PodList{}
				g.Expect(cli.List(ctx, list, runtimeCli.InNamespace(s.Namespace), runtimeCli.MatchingLabels{labels.LabelAppComponent: ctlogAction.ComponentName})).To(Succeed())
				for _, p := range list.Items {
					if p.CreationTimestamp.After(runningTimestamp) {
						return true
					}
				}
				return false

			}).Should(BeTrue())
		})

		It("Verify ctlog is in Ready state", func(ctx SpecContext) {
			Eventually(func(g Gomega) bool {
				c := ctlog.Get(ctx, cli, namespace.Name, s.Name)
				if c == nil {
					return false
				}

				for _, condition := range c.Status.Conditions {
					if condition.Type == "Ready" && condition.Status == metav1.ConditionTrue {
						return true
					}
				}
				return false
			}).Should(BeTrue())
		})

		It("Verify PKCS#11 sharding config is persisted", func(ctx SpecContext) {
			c := ctlog.Get(ctx, cli, namespace.Name, s.Name)
			Expect(c).ToNot(BeNil())
			Expect(c.Spec.Sharding).To(HaveLen(2))

			// Verify file shard
			fileShard := c.Spec.Sharding[0]
			Expect(fileShard.Type).To(Equal("file"))
			Expect(fileShard.Prefix).To(Equal("shard-0"))
			Expect(fileShard.PrivateKeyRef).ToNot(BeNil())

			// Verify PKCS#11 shard
			pkcs11Shard := c.Spec.Sharding[1]
			Expect(pkcs11Shard.Type).To(Equal("pkcs11"))
			Expect(pkcs11Shard.Prefix).To(Equal("shard-hsm"))
			Expect(pkcs11Shard.ModulePath).To(Equal("/usr/lib/softhsm/libsofthsm2.so"))
			Expect(pkcs11Shard.TokenLabel).To(Equal("test-ctlog-hsm"))
			Expect(pkcs11Shard.PinSecretRef).ToNot(BeNil())
			Expect(pkcs11Shard.PublicKeyRef).ToNot(BeNil())
		})

		It("Verify PKCS#11 sharding config is correctly marshaled in server config", func(ctx SpecContext) {
			c := ctlog.Get(ctx, cli, namespace.Name, s.Name)
			Expect(c).ToNot(BeNil())
			Expect(c.Status.ServerConfigRef).ToNot(BeNil())

			configSecret, err := kubernetes.GetSecret(ctx, cli, namespace.Name, c.Status.ServerConfigRef.Name)
			Expect(err).ToNot(HaveOccurred())
			Expect(configSecret).ToNot(BeNil())

			// Verify server config contains protobuf with correct shards
			configData, ok := configSecret.Data["config"]
			Expect(ok).To(BeTrue())
			Expect(configData).ToNot(BeEmpty())

			cfg := &configpb.LogMultiConfig{}
			Expect(prototext.Unmarshal(configData, cfg)).To(Succeed())
			Expect(cfg.LogConfigs).ToNot(BeNil())
			Expect(cfg.LogConfigs.Config).To(HaveLen(3)) // 2 shards + 1 active

			// Verify file shard marshaled correctly
			fileCfg := cfg.LogConfigs.Config[0]
			Expect(fileCfg.LogId).To(Equal(*oldTreeId))
			Expect(fileCfg.Prefix).To(Equal("shard-0"))
			Expect(fileCfg.IsReadonly).To(BeTrue())
			Expect(fileCfg.PrivateKey).ToNot(BeNil())
			filePrivateKey := &keyspb.PEMKeyFile{}
			Expect(anypb.UnmarshalTo(fileCfg.PrivateKey, filePrivateKey, proto.UnmarshalOptions{})).To(Succeed())
			Expect(filePrivateKey.Path).To(ContainSubstring("private"))

			// Verify PKCS#11 shard marshaled correctly
			pkcs11Cfg := cfg.LogConfigs.Config[1]
			Expect(pkcs11Cfg.LogId).To(Equal(*oldTreeId + 1))
			Expect(pkcs11Cfg.Prefix).To(Equal("shard-hsm"))
			Expect(pkcs11Cfg.IsReadonly).To(BeTrue())
			Expect(pkcs11Cfg.PrivateKey).ToNot(BeNil())
			pkcs11PrivateKey := &keyspb.PKCS11Config{}
			Expect(anypb.UnmarshalTo(pkcs11Cfg.PrivateKey, pkcs11PrivateKey, proto.UnmarshalOptions{})).To(Succeed())
			Expect(pkcs11PrivateKey.TokenLabel).To(Equal("test-ctlog-hsm"))
		})
	})
})
