//go:build integration

package install

import (
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/certificate-transparency-go/trillian/ctfe/configpb"
	"github.com/google/trillian/crypto/keyspb"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	rhtasv1 "github.com/securesign/operator/api/v1"
	ctlogAction "github.com/securesign/operator/internal/controller/ctlog/actions"
	"github.com/securesign/operator/internal/labels"
	"github.com/securesign/operator/internal/utils/kubernetes"
	"github.com/securesign/operator/test/e2e/support"
	testKubernetes "github.com/securesign/operator/test/e2e/support/kubernetes"
	"github.com/securesign/operator/test/e2e/support/postgresql"
	"github.com/securesign/operator/test/e2e/support/steps"
	"github.com/securesign/operator/test/e2e/support/tas"
	"github.com/securesign/operator/test/e2e/support/tas/ctlog"
	"github.com/securesign/operator/test/e2e/support/tas/securesign"
	"google.golang.org/protobuf/encoding/prototext"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/known/timestamppb"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/utils/ptr"
	runtimeCli "sigs.k8s.io/controller-runtime/pkg/client"
)

var _ = Describe("CTlog sharding configuration", Ordered, func() {
	SetDefaultEventuallyTimeout(time.Duration(10) * time.Minute)
	cli, _ := support.CreateClient()

	var namespace *v1.Namespace
	var s *rhtasv1.Securesign
	var fipsEnabled bool
	var runningTimestamp time.Time
	var newTreeId int64

	BeforeAll(steps.DetectAndConfigureFIPS(cli, func(enabled bool) {
		fipsEnabled = enabled
	}))

	BeforeAll(steps.CreateNamespace(cli, func(new *v1.Namespace) {
		namespace = new
	}))

	BeforeAll(func(ctx SpecContext) {
		if fipsEnabled {
			Expect(postgresql.CreateDB(ctx, cli, namespace.Name, postgresql.DefaultSecretName, "fips-password")).To(Succeed())
			postgresql.WaitAndLoadSchema(ctx, cli, namespace.Name)
		}
	})

	BeforeAll(func(ctx SpecContext) {
		s = securesign.Create(namespace.Name, "test",
			securesign.ChooseDefaults(fipsEnabled, namespace.Name),
		)
	})

	Describe("Install with autogenerated certificates", func() {
		BeforeAll(func(ctx SpecContext) {
			Expect(cli.Create(ctx, s)).To(Succeed())
		})

		It("All other components are running", func(ctx SpecContext) {
			tas.VerifyAllComponents(ctx, cli, s, !fipsEnabled, true)
			runningTimestamp = time.Now()
		})
	})

	Describe("Configure CTlog sharding", func() {
		var oldTreeId *int64
		var oldConfig *v1.Secret
		var oldPublicKey []byte

		It("Get current ctlog tree information", func(ctx SpecContext) {
			c := ctlog.Get(ctx, cli, namespace.Name, s.Name)
			Expect(c).ToNot(BeNil())
			oldTreeId = c.Status.TreeID
			Expect(oldTreeId).ToNot(BeNil())

			var err error
			oldConfig, err = kubernetes.GetSecret(ctx, cli, namespace.Name, c.Status.ServerConfigRef.Name)
			Expect(err).ToNot(HaveOccurred())
			Expect(oldConfig).ToNot(BeNil())

			oldPublicKey = oldConfig.Data["public"]
			Expect(oldPublicKey).ToNot(BeEmpty())
		})

		It("Freeze the current tree", func(ctx SpecContext) {
			drainingPod := updateTree(namespace.Name, oldTreeId, "DRAINING")
			Expect(cli.Create(ctx, drainingPod)).To(Succeed())
			Eventually(func(gomega Gomega) bool {
				gomega.Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(drainingPod), drainingPod)).To(Succeed())
				return drainingPod.Status.Phase == v1.PodSucceeded
			}).Should(BeTrue())

			freezePod := updateTree(namespace.Name, oldTreeId, "FROZEN")
			Expect(cli.Create(ctx, freezePod)).To(Succeed())
			Eventually(func(gomega Gomega) bool {
				gomega.Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(freezePod), freezePod)).To(Succeed())
				return freezePod.Status.Phase == v1.PodSucceeded
			}).Should(BeTrue())
		})

		It("Create new tree for active log", func(ctx SpecContext) {
			createPod := createTree(namespace.Name, "ctlog-sharding-tree")
			Expect(cli.Create(ctx, createPod)).To(Succeed())
			Eventually(func(gomega Gomega) bool {
				gomega.Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(createPod), createPod)).To(Succeed())
				return createPod.Status.Phase == v1.PodSucceeded
			}).Should(BeTrue())

			createTreeLog, err := testKubernetes.GetPodLogs(ctx, createPod.Name, "createtree", namespace.Name)
			Expect(err).ToNot(HaveOccurred())
			lines := strings.Split(strings.TrimSpace(createTreeLog), "\n")
			newTreeId, err = strconv.ParseInt(lines[len(lines)-1], 10, 64)
			Expect(err).ToNot(HaveOccurred())
		})

		It("Configure sharding with new tree", func(ctx SpecContext) {

			Eventually(func() error {
				s := securesign.Get(ctx, cli, namespace.Name, "test")

				if newTreeId == 0 {
					return fmt.Errorf("new tree ID not set")
				}

				secretName := "ctlog-sharding-config"
				newCtlogSecret := ctlog.CreateSecretWithPassword(namespace.Name, secretName)

				// Prepare config with sharding
				cfg := &configpb.LogMultiConfig{}
				now := time.Now()
				timestamp := &timestamppb.Timestamp{
					Seconds: now.Unix(), Nanos: int32(now.Nanosecond()),
				}
				Expect(prototext.Unmarshal(oldConfig.Data["config"], cfg)).To(Succeed())

				// First config entry is the frozen shard
				frozen := cfg.LogConfigs.Config[0]
				Expect(frozen).ToNot(BeNil())

				// Store the old tree ID before modifying
				frozenTreeId := frozen.LogId

				// Create a copy for the active shard
				cfg.LogConfigs.Config = append(cfg.LogConfigs.Config, proto.Clone(frozen).(*configpb.LogConfig))
				active := cfg.LogConfigs.Config[1]

				// Configure the frozen shard
				frozen.LogId = frozenTreeId // Ensure LogId is set correctly
				frozen.NotAfterLimit = timestamp
				frozen.Prefix = "trusted-artifact-signer-shard-0"
				frozenKey := &keyspb.PEMKeyFile{}
				Expect(anypb.UnmarshalTo(frozen.PrivateKey, frozenKey, proto.UnmarshalOptions{})).To(Succeed())
				frozenKey.Path = "/ctfe-keys/private-0"
				frozenAnyKey, err := anypb.New(frozenKey)
				Expect(err).ToNot(HaveOccurred())
				frozen.PrivateKey = frozenAnyKey

				// Configure the active shard
				active.LogId = newTreeId
				active.Prefix = "trusted-artifact-signer"
				activeAnyKey, err := anypb.New(&keyspb.PEMKeyFile{
					Path:     "/ctfe-keys/private",
					Password: string(newCtlogSecret.Data["password"]),
				})
				Expect(err).ToNot(HaveOccurred())
				active.PrivateKey = activeAnyKey
				active.PublicKey = nil
				active.NotAfterStart = timestamp

				configdata, err := prototext.Marshal(cfg)
				Expect(err).ToNot(HaveOccurred())
				newCtlogSecret.Data["config"] = configdata
				newCtlogSecret.Data["fulcio"] = oldConfig.Data["fulcio"]
				newCtlogSecret.Data["private-0"] = oldConfig.Data["private"]
				newCtlogSecret.Data["public-0"] = oldConfig.Data["public"]

				Expect(cli.Create(ctx, newCtlogSecret)).To(Succeed())

				// Update securesign resource with new tree and sharding config
				Expect(cli.Get(ctx, runtimeCli.ObjectKeyFromObject(s), s)).To(Succeed())

				s.Spec.Ctlog.TreeID = ptr.To(newTreeId)

				if s.Spec.Ctlog.Signer.File == nil {
					s.Spec.Ctlog.Signer.File = &rhtasv1.CTlogFile{}
				}
				s.Spec.Ctlog.Signer.File.PrivateKeyRef = &rhtasv1.SecretKeySelector{
					LocalObjectReference: rhtasv1.LocalObjectReference{
						Name: secretName,
					},
					Key: "private",
				}

				s.Spec.Ctlog.Signer.File.PublicKeyRef = &rhtasv1.SecretKeySelector{
					LocalObjectReference: rhtasv1.LocalObjectReference{
						Name: secretName,
					},
					Key: "public",
				}

				// Add sharding configuration
				s.Spec.Ctlog.Sharding = []rhtasv1.CTlogLogRange{
					{
						TreeID: *oldTreeId,
						Type:   "file",
						Prefix: "shard-0",
						PublicKeyRef: &rhtasv1.SecretKeySelector{
							LocalObjectReference: rhtasv1.LocalObjectReference{
								Name: secretName,
							},
							Key: "public-0",
						},
						PrivateKeyRef: rhtasv1.SecretKeySelector{
							LocalObjectReference: rhtasv1.LocalObjectReference{
								Name: secretName,
							},
							Key: "private-0",
						},
					},
				}

				return cli.Update(ctx, s)
			}).Should(Succeed())
		})

		It("Verify CTlog deployment is updated with sharding config", func(ctx SpecContext) {
			Eventually(func(g Gomega) bool {
				list := &v1.PodList{}
				g.Expect(cli.List(ctx, list, runtimeCli.InNamespace(s.Namespace), runtimeCli.MatchingLabels{labels.LabelAppComponent: ctlogAction.ComponentName})).To(Succeed())
				for _, p := range list.Items {
					if p.CreationTimestamp.After(runningTimestamp) {
						return true
					}
				}
				return false
			}).Should(BeTrue())
		})

		It("Verify ctlog is in Ready state", func(ctx SpecContext) {
			Eventually(func(g Gomega) bool {
				c := ctlog.Get(ctx, cli, namespace.Name, s.Name)
				if c == nil {
					return false
				}
				// Check that ctlog has the new tree ID
				return c.Status.TreeID != nil && *c.Status.TreeID != *oldTreeId
			}, time.Duration(5)*time.Minute).Should(BeTrue())
		})

		It("Verify sharding config is applied in the secret", func(ctx SpecContext) {
			c := ctlog.Get(ctx, cli, namespace.Name, s.Name)
			Expect(c).ToNot(BeNil())

			configSecret, err := kubernetes.GetSecret(ctx, cli, namespace.Name, c.Status.ServerConfigRef.Name)
			Expect(err).ToNot(HaveOccurred())

			cfg := &configpb.LogMultiConfig{}
			Expect(prototext.Unmarshal(configSecret.Data["config"], cfg)).To(Succeed())

			// Verify we have two log configs (frozen + active)
			Expect(cfg.LogConfigs.Config).To(HaveLen(2))

			// Verify frozen shard has the old tree ID
			frozenCfg := cfg.LogConfigs.Config[0]
			Expect(frozenCfg.LogId).To(Equal(*oldTreeId))
			Expect(frozenCfg.IsReadonly).To(BeTrue())

			// Verify active shard has the new tree ID
			activeCfg := cfg.LogConfigs.Config[1]
			Expect(activeCfg.LogId).To(Equal(*c.Status.TreeID))
			Expect(activeCfg.IsReadonly).To(BeFalse())
		})
	})
})

func updateTree(namespace string, treeId *int64, state string) *v1.Pod {
	args := []string{
		"--admin_server", fmt.Sprintf("trillian-logserver.%s.svc:8091", namespace),
		"--tree_id", strconv.FormatInt(*treeId, 10),
		"--tree_state", state,
	}
	if testKubernetes.IsRemoteClusterOpenshift() {
		args = append(args, "--tls_cert_file", "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt")
	}

	return &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			GenerateName: "update-tree-",
			Namespace:    namespace,
		},
		Spec: v1.PodSpec{
			RestartPolicy: v1.RestartPolicyNever,
			Containers: []v1.Container{
				{
					Name:    "updatetree",
					Image:   "registry.redhat.io/rhtas/updatetree-rhel9:1.1.0",
					Command: []string{"updatetree"},
					Args:    args,
					SecurityContext: &v1.SecurityContext{
						AllowPrivilegeEscalation: ptr.To(false),
						Capabilities:             &v1.Capabilities{Drop: []v1.Capability{"ALL"}},
						RunAsNonRoot:             ptr.To(true),
						SeccompProfile:           &v1.SeccompProfile{Type: v1.SeccompProfileTypeRuntimeDefault},
					},
				},
			},
		},
	}
}

func createTree(namespace, displayName string) *v1.Pod {
	args := []string{
		"--admin_server", fmt.Sprintf("trillian-logserver.%s.svc:8091", namespace),
		"--display_name", displayName,
	}
	if testKubernetes.IsRemoteClusterOpenshift() {
		args = append(args, "--tls_cert_file", "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt")
	}
	return &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			GenerateName: "create-tree-",
			Namespace:    namespace,
		},
		Spec: v1.PodSpec{
			RestartPolicy: v1.RestartPolicyNever,
			Containers: []v1.Container{
				{
					Name:    "createtree",
					Image:   "registry.redhat.io/rhtas/createtree-rhel9:1.1.0",
					Command: []string{"createtree"},
					Args:    args,
					SecurityContext: &v1.SecurityContext{
						AllowPrivilegeEscalation: ptr.To(false),
						Capabilities:             &v1.Capabilities{Drop: []v1.Capability{"ALL"}},
						RunAsNonRoot:             ptr.To(true),
						SeccompProfile:           &v1.SeccompProfile{Type: v1.SeccompProfileTypeRuntimeDefault},
					},
				},
			},
		},
	}
}
