# Trillian
- op: add
  path: "/spec/customresourcedefinitions/owned/5/specDescriptors"
  value:
    - description: The desired number of member Pods.
      displayName: Replicas
      path: server.replicas
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podCount'
    - description: Limits describes the minimum/maximum amount of compute resources required/allowed
      displayName: Resource Requirements
      path: server.resources
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:resourceRequirements'
    - displayName: Node Affinity
      description: Node affinity is a group of node affinity scheduling
      path: server.affinity.nodeAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:nodeAffinity'
    - displayName: Pod Affinity
      description: Pod affinity is a group of inter pod affinity scheduling rules.
      path: server.affinity.podAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podAffinity'
    - displayName: Pod Anti Affinity
      description: Pod anti affinity is a group of inter pod anti affinity scheduling rules.
      path: server.affinity.podAntiAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podAntiAffinity'
    - description: The desired number of member Pods.
      displayName: Replicas
      path: signer.replicas
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podCount'
    - description: Limits describes the minimum/maximum amount of compute resources required/allowed
      displayName: Resource Requirements
      path: signer.resources
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:resourceRequirements'
    - displayName: Node Affinity
      description: Node affinity is a group of node affinity scheduling
      path: signer.affinity.nodeAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:nodeAffinity'
    - displayName: Pod Affinity
      description: Pod affinity is a group of inter pod affinity scheduling rules.
      path: signer.affinity.podAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podAffinity'
    - displayName: Pod Anti Affinity
      description: Pod anti affinity is a group of inter pod anti affinity scheduling rules.
      path: signer.affinity.podAntiAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podAntiAffinity'

# Securesign
- op: add
  path: "/spec/customresourcedefinitions/owned/3/specDescriptors"
  value:
    - description: The desired number of member Pods.
      displayName: Replicas
      path: trillian.server.replicas
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podCount'
    - description: Limits describes the minimum/maximum amount of compute resources required/allowed
      displayName: Resource Requirements
      path: trillian.server.resources
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:resourceRequirements'
    - displayName: Node Affinity
      description: Node affinity is a group of node affinity scheduling
      path: trillian.server.affinity.nodeAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:nodeAffinity'
    - displayName: Pod Affinity
      description: Pod affinity is a group of inter pod affinity scheduling rules.
      path: trillian.server.affinity.podAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podAffinity'
    - displayName: Pod Anti Affinity
      description: Pod anti affinity is a group of inter pod anti affinity scheduling rules.
      path: trillian.server.affinity.podAntiAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podAntiAffinity'
    - description: The desired number of member Pods.
      displayName: Replicas
      path: trillian.signer.replicas
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podCount'
    - description: Limits describes the minimum/maximum amount of compute resources required/allowed
      displayName: Resource Requirements
      path: trillian.signer.resources
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:resourceRequirements'
    - displayName: Node Affinity
      description: Node affinity is a group of node affinity scheduling
      path: trillian.signer.affinity.nodeAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:nodeAffinity'
    - displayName: Pod Affinity
      description: Pod affinity is a group of inter pod affinity scheduling rules.
      path: trillian.signer.affinity.podAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podAffinity'
    - displayName: Pod Anti Affinity
      description: Pod anti affinity is a group of inter pod anti affinity scheduling rules.
      path: trillian.signer.affinity.podAntiAffinity
      x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podAntiAffinity'
