# Mirror registry.redhat.io/rhtas images to quay.io/securesign for development.
# Copy to /etc/containers/registries.conf.d/rhtas-dev-mirrors.conf on each node.

[[registry]]
location = "registry.redhat.io/rhtas/certificate-transparency-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/certificate-transparency-go"

[[registry]]
location = "registry.redhat.io/rhtas/rhtas-operator-bundle"
[[registry.mirror]]
location = "quay.io/securesign/rhtas-operator-bundle"

[[registry]]
location = "registry.redhat.io/rhtas/rhtas-rhel9-operator"
[[registry.mirror]]
location = "quay.io/securesign/rhtas-operator"

[[registry]]
location = "registry.redhat.io/rhtas/fulcio-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/fulcio-server"

[[registry]]
location = "registry.redhat.io/rhtas/rekor-server-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/rekor-server"

[[registry]]
location = "registry.redhat.io/rhtas/rekor-backfill-redis-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/rekor-backfill-redis"

[[registry]]
location = "registry.redhat.io/rhtas/rekor-search-ui-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/rekor-search-ui"

[[registry]]
location = "registry.redhat.io/rhtas/trillian-logserver-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/trillian-logserver"

[[registry]]
location = "registry.redhat.io/rhtas/trillian-logsigner-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/trillian-logsigner"

[[registry]]
location = "registry.redhat.io/rhtas/trillian-database-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/trillian-database"

[[registry]]
location = "registry.redhat.io/rhtas/trillian-redis-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/trillian-redis"

[[registry]]
location = "registry.redhat.io/rhtas/createtree-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/trillian-createtree"

[[registry]]
location = "registry.redhat.io/rhtas/segment-reporting-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/segment-backup-job"

[[registry]]
location = "registry.redhat.io/rhtas/timestamp-authority-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/timestamp-authority"

[[registry]]
location = "registry.redhat.io/rhtas/rekor-monitor-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/rekor-monitor"

[[registry]]
location = "registry.redhat.io/rhtas/tuffer-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/tuffer"

[[registry]]
location = "registry.redhat.io/rhtas/ctlog-monitor-rhel9"
[[registry.mirror]]
location = "quay.io/securesign/ctlog-monitor"
