apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default

patches:
  - path: manager_openshift_patch.yaml
    target:
      kind: Deployment
      name: operator-controller-manager
