apiVersion: apps/v1
kind: Deployment
metadata:
  name:  operator-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: OPENSHIFT
              value: "true"
