apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: controllers/constants/*
    build.appstudio.openshift.io/repo: https://github.com/securesign/secure-sign-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && (".tekton/rhtas-operator-bundle-pull-request.yaml".pathChanged() || ".tekton/rhtas-operator-pull-request.yaml".pathChanged()
      || "bundle.Dockerfile".pathChanged() || "Dockerfile.rhtas-operator.rh".pathChanged()
      || "config/***".pathChanged() || "hack/***".pathChanged()
      || "api/***".pathChanged() || "internal/***".pathChanged() || "cmd/***".pathChanged()
      || "test/***".pathChanged()
      || "go.mod".pathChanged() || "go.sum".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: operator
    appstudio.openshift.io/component: rhtas-operator
    pipelines.appstudio.openshift.io/type: build
  name: rhtas-operator-on-pull-request
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/rhtas-operator:on-pr-{{revision}}
  # Add these parameters
  - name: sealights-output-image
    value: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator-sealights:{{revision}}
  - name: sealights-dockerfile
    value: Dockerfile.sealights
  - name: sealights-image-expires-after
    value: '5d'
  - name: dockerfile
    value: Dockerfile.rhtas-operator.rh
  - name: path-context
    value: .
  - name: component
    value: '{{ repo_name }}'
  - name: branch
    value: '{{ source_branch }}'
  - name: revision
    value: '{{ revision }}'
  - name: repository-url
    value: '{{ repo_url }}'
  - name: test-event
    value: '{{ event_type }}'
  - name: pull-request-number
    value: '{{ pull_request_number }}'
  - name: target-branch
    value: '{{ target_branch }}'
  - name: build-platforms
    value:
    - linux/x86_64
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: '{"type": "gomod", "path": "."}'
  - name: image-expires-after
    value: 5d
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: SealightsExperimental
    - name: pathInRepo
      value: pipelines/docker-build-multi-platform-oci-ta.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-rhtas-operator
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
