apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: internal/controller/constants/*
    build.appstudio.openshift.io/repo: https://github.com/securesign/secure-sign-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ("config/***".pathChanged() || ".tekton/bundle-build-pipeline.yaml".pathChanged()
      || ".tekton/rhtas-operator-bundle-push.yaml".pathChanged() || "bundle.Dockerfile".pathChanged()
      || "trigger-konflux-builds.txt".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: operator
    appstudio.openshift.io/component: rhtas-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: rhtas-operator-bundle-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/rhtas-operator-bundle:{{revision}}
  - name: dockerfile
    value: bundle.Dockerfile
  - name: path-context
    value: .
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: ""
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-rhtas-operator-bundle
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
