//go:build integration

package e2e

import (
	"github.com/securesign/operator/test/e2e/support/steps"
	"github.com/securesign/operator/test/e2e/support/tas"
	"github.com/securesign/operator/test/e2e/support/tas/cosign"
	"github.com/securesign/operator/test/e2e/support/tas/securesign"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/securesign/operator/api/v1alpha1"
	"github.com/securesign/operator/test/e2e/support"
	v1 "k8s.io/api/core/v1"
)

var _ = Describe("Securesign install with in-cluster services and internal TUF signing config", Ordered, func() {
	cli, _ := support.CreateClient()

	var namespace *v1.Namespace
	var s *v1alpha1.Securesign
	var targetImageName string

	BeforeAll(steps.CreateNamespace(cli, func(new *v1.Namespace) {
		namespace = new
	}))

	BeforeAll(func(ctx SpecContext) {
		s = securesign.Create(namespace.Name, "test",
			securesign.WithTSA(),
			securesign.WithGeneratedCerts(),
			securesign.WithManagedDatabase(),
			securesign.WithDefaultOIDC(),
			securesign.WithNTPMonitoring(),
		)
	})

	BeforeAll(func(ctx SpecContext) {
		targetImageName = support.PrepareImage(ctx)
	})

	Describe("Install with autogenerated certificates (no external routes)", func() {
		BeforeAll(func(ctx SpecContext) {
			Expect(cli.Create(ctx, s)).To(Succeed())
		})

		It("All other components are running", func(ctx SpecContext) {
			tas.VerifyAllComponents(ctx, cli, s, true)
		})

		It("Securesign status exposes in-cluster service URLs", func(ctx SpecContext) {
			s = securesign.Get(ctx, cli, namespace.Name, s.Name)
			Expect(s.Status.TufStatus.Url).To(ContainSubstring(".svc"))
			Expect(s.Status.FulcioStatus.Url).To(ContainSubstring(".svc"))
			Expect(s.Status.RekorStatus.Url).To(ContainSubstring(".svc"))
			Expect(s.Status.TSAStatus.Url).To(ContainSubstring(".svc"))
		})

		It("Sign image with cosign cli", func(ctx SpecContext) {
			cosign := cosign.NewInClusterCosign(namespace.Name, s.Status.TufStatus.Url, cli)
			cosign.VerifyByCosign(ctx, targetImageName)
		})

	})
})
