apiVersion: v1
kind: Service
metadata:
  name: keycloak-internal
spec:
  selector:
    app: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
