apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: cosign
  labels:
    app.kubernetes.io/part-of: trusted-artifact-signer
spec:
  displayName: "cosign - Command Line Interface (CLI)"
  description: "cosign is a CLI tool that allows you to manage sigstore artifacts."
  links:
    - text: "Download cosign for Linux x86_64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/cosign_linux_amd64.tar.gz"
    - text: "Download cosign for Linux arm64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/cosign_linux_arm64.tar.gz"
    - text: "Download cosign for Linux ppc64le"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/cosign_linux_ppc64le.tar.gz"
    - text: "Download cosign for Linux s390x"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/cosign_linux_s390x.tar.gz"
    - text: "Download cosign for Mac x86_64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/cosign_darwin_amd64.tar.gz"
    - text: "Download cosign for Mac arm64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/cosign_darwin_arm64.tar.gz"
    - text: "Download cosign for Windows x86_64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/cosign_windows_amd64.zip"
