apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: fetch-tsa-certs
  labels:
    app.kubernetes.io/part-of: trusted-artifact-signer
spec:
  displayName: "fetch-tsa-certs - Command Line Interface (CLI)"
  description: "fetch-tsa-certs is a cli used to configure the kms and tink signer types for Timestamp Authority."
  links:
    - text: "Download fetch-tsa-certs for Linux x86_64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/fetch_tsa_certs_linux_amd64.tar.gz"
    - text: "Download fetch-tsa-certs for Linux arm64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/fetch_tsa_certs_linux_arm64.tar.gz"
    - text: "Download fetch-tsa-certs for Linux ppc64le"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/fetch_tsa_certs_linux_ppc64le.tar.gz"
    - text: "Download fetch-tsa-certs for Linux s390x"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/fetch_tsa_certs_linux_s390x.tar.gz"
    - text: "Download fetch-tsa-certs for Mac x86_64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/fetch_tsa_certs_darwin_amd64.tar.gz"
    - text: "Download fetch-tsa-certs for Mac arm64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/fetch_tsa_certs_darwin_arm64.tar.gz"
    - text: "Download fetch-tsa-certs for Windows x86_64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/fetch_tsa_certs_windows_amd64.zip"
