apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: gitsign
  labels:
    app.kubernetes.io/part-of: trusted-artifact-signer
spec:
  displayName: "gitsign - Command Line Interface (CLI)"
  description: "gitsign is a CLI tool that allows you to digitally sign and verify git commits."
  links:
    - text: "Download gitsign for Linux x86_64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/gitsign_cli_linux_amd64.tar.gz"
    - text: "Download gitsign for Linux arm64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/gitsign_cli_linux_arm64.tar.gz"
    - text: "Download gitsign for Linux ppc64le"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/gitsign_cli_linux_ppc64le.tar.gz"
    - text: "Download gitsign for Linux s390x"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/gitsign_cli_linux_s390x.tar.gz"
    - text: "Download gitsign for Mac x86_64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/gitsign_cli_darwin_amd64.tar.gz"
    - text: "Download gitsign for Mac arm64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/gitsign_cli_darwin_arm64.tar.gz"
    - text: "Download gitsign for Windows x86_64"
      href: "https://developers.redhat.com/content-gateway/file/RHTAS/__VERSION__/gitsign_cli_windows_amd64.zip"
