apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cosign.yaml
- rekor-cli.yaml
- gitsign.yaml
- ec.yaml
- fetch-tsa-certs.yaml
- createtree.yaml
- updatetree.yaml
- tuftool.yaml
- tufcli.yaml
