apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: rekor-cli
spec:
  displayName: "rekor-cli - Command Line Interface (CLI)"
  description: "rekor-cli is a CLI tool that allows you to interact with rekor server."
  links:
    - text: "Download rekor-cli for Linux x86_64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/rekor_cli_linux_amd64.tar.gz"
    - text: "Download rekor-cli for Linux arm64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/rekor_cli_linux_arm64.tar.gz"
    - text: "Download rekor-cli for Linux ppc64le"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/rekor_cli_linux_ppc64le.tar.gz"
    - text: "Download rekor-cli for Linux s390x"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/rekor_cli_linux_s390x.tar.gz"
    - text: "Download rekor-cli for Mac x86_64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/rekor_cli_darwin_amd64.tar.gz"
    - text: "Download rekor-cli for Mac arm64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/rekor_cli_darwin_arm64.tar.gz"
    - text: "Download rekor-cli for Windows x86_64"
      href: "https://developers.redhat.com/content-gateway/file/cgw/RHTAS/__VERSION__/rekor_cli_windows_amd64.zip"
